language: node_js
node_js:
  - "node"
cache:
    directories:
      - node_modules

addons:
    code_climate:
      repo_token: ce02b8f433bcfcf474b8cb3e6bc363b07fc9dc5ecc229de03df6c0fc212bad93

jobs:
    include:
      - script: ./node_modules/.bin/eslint .;
      - script: npm test -- --coverage;
      - stage: deploy
        script: npm run build;
        deploy:
          provider: pages
          local_dir: build/
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          on:
            branch: master


after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
